groups:
  - name: twitter_publisher_alerts
    rules:
      - alert: HighCPUUsage
        expr: cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes"
      
      - alert: HighMemoryUsage
        expr: memory_usage_percent > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes"
      
      - alert: PublishingFailures
        expr: publishing_failures_total > 5
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Multiple publishing failures"
          description: "More than 5 publishing failures in the last 10 minutes"