# 端口配置
ports:
  # 端口配置
api_port: 8050
frontend_port: 8080
prometheus_port: 9090
grafana_port: 3000

analytics:
  detailed_metrics: true
  enabled: true
  export_enabled: true
  report_interval_hours: 24
  retention_days: 90
database:
  auto_vacuum: true
  backup_enabled: true
  backup_interval_hours: 24
  backup_retention_days: 30
  connection_timeout: 30
  pool_size: 10
  path: ./data/twitter_publisher.db
environment: production
gemini:
  api_key: ''
  max_tokens: 1000
  model: gemini-pro
  temperature: 0.7
  timeout_seconds: 30
logging:
  backup_count: 5
  enable_console: true
  enable_file: true
  path: ./logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_size_mb: 100
notifications:
  email:
    enabled: false
    from_email: ''
    password: ''
    smtp_port: 587
    smtp_server: ''
    to_emails: []
    username: ''
  webhook:
    enabled: false
    secret: ''
    url: ''
performance:
  alert_thresholds:
    cpu_percent: 80
    disk_percent: 90
    memory_percent: 85
    response_time_ms: 5000
  batch_size: 10
  cache_enabled: true
  cache_ttl_seconds: 3600
  connection_pool_size: 20
  metrics_retention_days: 30
  monitoring_enabled: true
project_base_path: ./project
publishing:
  content_validation: true
  default_language: en
  duplicate_detection: true
  enable_preview_mode: false
  max_retries: 3
  retry_delay_minutes: 15
  use_ai_enhancement: true
retry:
  base_delay_seconds: 60
  exponential_backoff: true
  jitter: true
  max_attempts: 5
  max_delay_seconds: 3600
scheduling:
  batch_size: 2       # 快速验证模式：减少批量大小到2个任务
  blackout_hours: []
  enable_smart_scheduling: true
  interval_hours: 0.25  # 快速验证模式：15分钟间隔（0.25小时）
  interval_minutes_min: 2
  interval_minutes_max: 5
  max_concurrent_tasks: 1      # 快速验证模式：单线程执行
  priority_projects: []
  task_timeout_minutes: 10
  check_interval: 30  # 快速验证模式：30秒检查间隔
  min_publish_interval: 180  # 快速验证模式：最小发布间隔3分钟
  batch_delay_min_seconds: 10   # 快速验证模式：批次任务间最小延迟10秒
  batch_delay_max_seconds: 30  # 快速验证模式：批次任务间最大延迟30秒
task_management:
  stuck_task_timeout_hours: 2
  max_retries: 3
  retry_backoff_base: 2
  lock_timeout_minutes: 30
  batch_size: 10
security:
  api_key_rotation_days: 90
  audit_logging: true
  encryption_enabled: false
  max_requests_per_minute: 30  # 快速验证模式：适当提高请求频率
  rate_limiting: true
  secure_headers: true
  api_timeout: 15  # 快速验证模式：减少超时时间
  retry_on_rate_limit: true
twitter:
  access_token: ''
  access_token_secret: ''
  api_version: '2'
  bearer_token: ''
  consumer_key: ''
  consumer_secret: ''
  timeout_seconds: 30
version: 2.0.0
